#pragma once
// Japanese string column (DECISIONS.md D19). Compiled only when ENABLE_CJK=1.
//
// One entry per StrId, in enum order (a static_assert below checks the count). Each
// line carries the English source as a comment so a translator does not have to open
// strings_i18n.h. nullptr = not translated yet: the UI shows the English string.
//
// THESE TRANSLATIONS ARE NOT REVIEWED BY A NATIVE SPEAKER. They are best-effort and
// published that way on purpose; corrections are very welcome (see docs/TRANSLATING.md).
//
// Kept out of strings_i18n.h on purpose: PackScope/tools/gen_locales.py parses that file
// and requires exactly four literals (EN/FR/DE/ES) per STRTAB row. Do not point
// gen_locales.py here; PackScope has its own Japanese catalog.
//
// Every non-ASCII character used here needs a glyph in glyphs_ja.h. After editing this
// file, regenerate it:  python tools/gen_cjk_glyphs.py
// A character with no glyph draws as a hollow box on the device.
#include "strings_i18n.h"

#if ENABLE_CJK
const char* const STRTAB_JA[] = {
  /*S_BATTERY*/               "バッテリー", // EN: "Battery"
  /*S_REPAIR*/                "修理", // EN: "Repair"
  /*S_TOOLS*/                 "ツール", // EN: "Tools"
  /*S_ABOUT*/                 "バージョン情報", // EN: "About"
  /*S_PC_BRIDGE*/             "PCブリッジ", // EN: "PC bridge"
  /*S_LEDS_ON*/               "パックLED点灯", // EN: "Pack LEDs on"
  /*S_LEDS_OFF*/              "パックLED消灯", // EN: "Pack LEDs off"
  /*S_RESET_ERROR*/           "エラーをリセット", // EN: "Reset error"
  /*S_DEBUG_RAW*/             "デバッグ / 生データ", // EN: "Debug / raw"
  /*S_SETTINGS*/              "設定", // EN: "Settings"
  /*S_FLIP*/                  "画面反転", // EN: "Flip screen"
  /*S_BRIDGE_BOOT*/           "起動時にPCブリッジ", // EN: "PC bridge at boot"
  /*S_LANGUAGE*/              "言語", // EN: "Language"
  /*S_HEALTHY*/               "正常", // EN: "HEALTHY"
  /*S_UNLOCK*/                "ロック解除", // EN: "UNLOCK"
  /*S_HARDWARE_FIX*/          "ハード修理", // EN: "HARDWARE FIX"
  /*S_SUSPECT_HW*/            "ハード修理の可能性", // EN: "POSSIBLE HW FIX"
  /*S_NO_PACK*/               "パックなし", // EN: "NO PACK"
  /*S_HDR_HEALTH*/            "健全性", // EN: "Health"
  /*S_HDR_IDENTITY*/          "識別情報", // EN: "Identity"
  /*S_PACK*/                  "パック", // EN: "PACK"
  /*S_TEMP*/                  "温度", // EN: "Temp"
  /*S_SPREAD*/                "温度差", // EN: "Spread"
  /*S_CHARGES*/               "充電回数", // EN: "Charges"
  /*S_CONDITION*/             "状態", // EN: "Condition"
  /*S_OVERDISCHARGE*/         "過放電", // EN: "Over-discharge"
  /*S_OVERLOAD*/              "過負荷", // EN: "Over-load"
  /*S_CELLS*/                 "セル", // EN: "Cells"
  /*S_LATCHED*/               "ラッチ", // EN: "Latched"
  /*S_MODEL*/                 "型式", // EN: "Model"
  /*S_SN*/                    "S/N", // EN: "S/N"
  /*S_CAPACITY*/              "容量", // EN: "Capacity"
  /*S_TYPE*/                  "種類", // EN: "Type"
  /*S_PRODUCED*/              "製造", // EN: "Produced"
  /*S_ASSEMBLED*/             "組立", // EN: "Assembled"
  /*S_NUM_CHARGES*/           "充電回数", // EN: "Number of charges"
  /*S_DATES_NOTE*/            "日付: YYYY-MM-DD", // EN: "dates: YYYY-MM-DD"
  /*S_CHARGER_LOCK*/          "充電ロック", // EN: "Charger lock"
  /*S_LATCHED_FAULT*/         "ラッチ故障", // EN: "Latched fault"
  /*S_THERMISTOR*/            "サーミスタ", // EN: "Thermistor"
  /*S_CELL_BALANCE*/          "セルバランス", // EN: "Cell balance"
  /*S_NONE*/                  "なし", // EN: "none"
  /*S_YES*/                   "はい", // EN: "yes"
  /*S_OKV*/                   "正常", // EN: "ok"
  /*S_FAULTV*/                "故障", // EN: "fault"
  /*S_BADV*/                  "不良", // EN: "bad"
  /*S_WILL_HOLD*/             "維持される", // EN: "WILL HOLD"
  /*S_WONT_HOLD*/             "維持されない", // EN: "WON'T HOLD"
  /*S_NOT_LOCKED*/            "ロックなし", // EN: "NOT LOCKED"
  /*S_HINT_CONT_CANCEL*/      "クリック＝続行  回す＝中止", // EN: "Click = continue    Turn = cancel"
  /*S_FRAME_VALID_NOTHING*/   "フレーム正常 - 修理不要", // EN: "Frame valid - nothing to repair"
  /*S_NOT_SUPPORTED*/         "F0513: 非対応", // EN: "F0513: not supported"
  /*S_HINT_CLICK_TURN_BACK*/  "（クリック／回す＝戻る）", // EN: "(click / turn = back)"
  /*S_FRAME_ALREADY_VALID*/   "フレームは既に正常。", // EN: "Frame already valid."
  /*S_NOTHING_NO_WRITE*/      "修理不要 - 書き込みなし。", // EN: "Nothing to repair - no write done."
  /*S_WARN_WRITES_FLASH*/     "警告: BMSのフラッシュに書き込みます。", // EN: "WARNING: writes to the BMS flash."
  /*S_REPAIRS_FALSE_ONLY*/    "修理できるのは誤ロックのみ。", // EN: "Repairs a false lockout only."
  /*S_CLICK_WRITE*/           "クリック＝書込", // EN: "Click = write"
  /*S_TURN_CANCEL*/           "回す＝中止", // EN: "Turn  = cancel"
  /*S_BEFORE*/                "前", // EN: "Before"
  /*S_AFTER*/                 "後", // EN: "After"
  /*S_NO_READ_AFTER*/         "-> 書込後の読取なし", // EN: "-> No read after write"
  /*S_UNLOCKED_RES*/          "-> ロック解除!", // EN: "-> Unlocked!"
  /*S_STILL_LOCKED*/          "-> まだロック中", // EN: "-> Still locked"
  /*S_RETRY_REINSERT*/        "再試行はパックを抜き差し。", // EN: "To retry, remove & reinsert the pack."
  /*S_RESET_ERROR_Q*/         "エラーをリセット？", // EN: "RESET ERROR?"
  /*S_CMD_SENT*/              "コマンド送信:", // EN: "Command sent:"
  /*S_CLICK_CONFIRM*/         "クリック＝確定", // EN: "Click = confirm"
  /*S_RESET_DONE*/            "リセット完了", // EN: "RESET DONE"
  /*S_ERR_CLEARED*/           "-> エラー解除!", // EN: "-> Error cleared!"
  /*S_UNCHANGED*/             "-> 変化なし", // EN: "-> Unchanged"
  /*S_STATE_ARROW*/           "-> 状態:", // EN: "-> State:"
  /*S_LOCKEDV*/               "ロック中", // EN: "LOCKED"
  /*S_OKSTATE*/               "正常", // EN: "OK"
  /*S_NO_ERROR*/              "-> 解除するエラーなし", // EN: "-> No error to clear"
  /*S_PC_MODE*/               "PCモード", // EN: "PC MODE"
  /*S_BRIDGE_ACTIVE*/         "USBブリッジ動作中", // EN: "USB bridge ACTIVE"
  /*S_BRIDGE_INACTIVE*/       "ブリッジ停止中", // EN: "bridge INACTIVE"
  /*S_PC_HELP1*/              "PCで Open Battery Information を", // EN: "Open 'Open Battery Information' on"
  /*S_PC_HELP2*/              "開き、Arduino OBI インターフェースと", // EN: "your PC, pick the Arduino OBI"
  /*S_PC_HELP3*/              "このCOMポートを選択してください。", // EN: "interface + this COM port."
  /*S_HINT_TURN_TOGGLE_EXIT*/ "（回す＝切替  戻る＝終了）", // EN: "(turn = toggle    back = exit)"
  /*S_SCAN*/                  "スキャン", // EN: "scan"
  /*S_HINT_CLICK_BACK*/       "クリック＝戻る", // EN: "click = back"
  /*S_HINT_CLICK_BACK_P*/     "（クリック＝戻る）", // EN: "(click = back)"
  /*S_COMM_ERROR_HDR*/        "通信エラー", // EN: "COMM ERROR"
  /*S_NO_RESPONSE*/           "バスに応答なし。", // EN: "No response on bus."
  /*S_CHECK_DATA*/            "DATA配線、プルアップ、", // EN: "Check DATA wiring,"
  /*S_CHECK_PULLUPS*/         "GNDを確認してください。", // EN: "pull-ups and GND."
  /*S_LEDS_ON_MSG*/           "LED点灯", // EN: "LEDs ON"
  /*S_LEDS_OFF_MSG*/          "LED消灯", // EN: "LEDs OFF"
  /*S_HINT_TOGGLE_SAVE*/      "クリック＝切替  戻る＝保存して終了", // EN: "click = toggle     back = save & exit"
  /*S_CANNOT_DIAG*/           "診断不可", // EN: "Cannot diagnose"
  /*S_NO_PACK_REPLY1*/        "パック応答なし。アダプタ、", // EN: "No pack reply. Check the adapter, the"
  /*S_NO_PACK_REPLY2*/        "DATA/ENABLE配線、BMS故障を確認。", // EN: "DATA/ENABLE wiring, or a dead BMS."
  /*S_NO_DIAGNOSIS*/          "診断なし", // EN: "NO DIAGNOSIS"
  /*S_HW_SENSE*/              "センス線断線", // EN: "Broken sense wire"
  /*S_HW_WEAK*/               "劣化／不良グループ", // EN: "Weak / dead group"
  /*S_HW_IMB*/                "セルアンバランス", // EN: "Cell imbalance"
  /*S_HW_THERM*/              "温度読み取り異常", // EN: "Temp reading off"
  /*S_ACT_SENSE*/             "グループ%dのセンス線を再はんだ付け", // EN: "Resolder sense wire on group %d"
  /*S_ACT_WEAK*/              "グループ%dをテスタで測定", // EN: "Measure group %d with a DMM"
  /*S_ACT_IMB*/               "グループ%d低下: 低速充電し再確認", // EN: "Group %d low: slow-charge, recheck"
  /*S_ACT_THERM*/             "冷えてから再読み取り、NTCを確認", // EN: "Re-read cold, then check NTC"
  /*S_FIX_HW_FIRST*/          "先にハード修理", // EN: "FIX HARDWARE FIRST"
  /*S_UNLIKELY_HOLD*/         "維持は困難", // EN: "UNLIKELY TO HOLD"
  /*S_SHOULD_HOLD*/           "維持の見込み", // EN: "SHOULD HOLD"
  /*S_NO_LOCK_NO_FAULT*/      "ロックなし・故障なし", // EN: "No lock, no fault"
  /*S_BMS_MEMORISED*/         "BMSが故障を記憶", // EN: "BMS memorised a fault"
  /*S_FALSE_LOCKOUT*/         "誤ロックアウト", // EN: "False lockout"
  /*S_PACK_HEALTHY*/          "パックは正常に見えます。", // EN: "Pack looks healthy."
  /*S_WHY_OD*/                "放置による過放電の可能性。", // EN: "Likely left flat (over-discharge)."
  /*S_WHY_OL*/                "過負荷使用の可能性。", // EN: "Likely run in overload."
  /*S_WHY_WEAR*/              "通常の消耗と一致。", // EN: "Consistent with normal wear."
  /*S_WHY_UNCLEAR*/           "原因不明 - 健全性カウンタ参照。", // EN: "Cause unclear - see Health counters."
  /*S_WHY_THERM_CHECK*/       "セル/基板の温度差 - 再確認", // EN: "Cell/board temps differ - recheck"
  /*S_UNLOCK_SHOULD_HOLD*/    "解除は維持されるはずです。", // EN: "Our unlock should hold."
  /*S_HINT_CONTINUE_BACK*/    "クリック＝続行  回す＝戻る", // EN: "Click = continue    Turn = back"
  /*S_HINT_FIXHW_BACK*/       "先にハード修理  回す＝戻る", // EN: "Fix hardware first   Turn = back"
  /*S_HINT_NOTHING_BACK*/     "修理不要  回す＝戻る", // EN: "Nothing to repair   Turn = back"
  /*S_TOAST_FIXHW*/           "先にハード修理", // EN: "Fix hardware first"
  /*S_TOAST_NOTHING*/         "修理不要", // EN: "Nothing to repair"
  /*S_WORKING*/               "処理中...", // EN: "Working..."
  /*S_FRAME_STORE_PC*/        "フレーム修復 -> 保存 -> 電源再投入", // EN: "repair frame  ->  store  ->  power-cycle"
  /*S_HINT_TAG*/              "ヒント", // EN: "HINT"
  /*S_TEMP_CB*/               "セル/基板", // EN: "Cell/Board"
  /*S_CALIBRATE*/             "タッチ調整", // EN: "Calibrate touch"
  /*S_CAL_TAP*/               "ターゲットをタップ", // EN: "Tap the target"
  /*S_CAL_SAVED*/             "保存しました", // EN: "Saved"
};
static_assert(sizeof(STRTAB_JA) / sizeof(STRTAB_JA[0]) == S_COUNT,
              "strings_ja.h: one entry per StrId, in enum order");
#endif // ENABLE_CJK
